# Generated by Django 4.2.16 on 2024-09-12 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_ouruserprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ouruserprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='ouruserprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='ouruserprofile',
            name='username',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preference1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preference2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preference3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preference4',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preference5',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
